# Generated by Django 5.0.6 on 2024-12-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='screenshot/'),
        ),
    ]
