# Generated by Django 5.0.6 on 2025-01-02 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='poster',
            new_name='agent',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'agent')},
        ),
    ]
