# Generated by Django 5.0.6 on 2025-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_poster_rating_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_image/profile.png', upload_to='profile_image/'),
        ),
    ]
