# Generated by Django 5.0.6 on 2025-01-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_payment_payment_intent_id_adminaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
    ]
