# Generated by Django 5.0.6 on 2025-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_property_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google',
            field=models.TextField(),
        ),
    ]
