# Generated by Django 5.0.6 on 2025-01-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_remove_profile_has_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('notavailable', 'Not available'), ('sold', 'Sold')], default='notavailable', max_length=15),
        ),
    ]
