# Generated by Django 5.0.6 on 2025-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/'),
        ),
    ]
